services:
  api:
    env_file:
      - secrets.prod.env
    depends_on:
      - db
    ports:
      - "127.0.0.1:8000:8000"
  ui:
    env_file:
      - secrets.prod.env
    ports:
      - "127.0.0.1:9000:9000"
  db:
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
