services:
  api:
    build: api
    ports:
      - "8000:8000"
    volumes:
      - refinance-api-data:/opt/data
    env_file:
      - secrets.env

  ui:
    build: ui
    ports:
      - "5000:5000"
    volumes:
      - refinance-api-data:/opt/data
    env_file:
      - secrets.env

volumes:
  refinance-api-data:
