services:
  api:
    build: api
    ports:
      - "8000:8000"
    volumes:
      - api-data:/opt/data
    env_file:
      - secrets.env

  ui:
    build: ui
    ports:
      - "5001:5000"
    env_file:
      - secrets.env

volumes:
  api-data:
