services:
  api:
    build: api
    ports:
      - "8000:8000"
    volumes:
      - api-data:/opt/data
    env_file:
      - secrets.env.example

  ui:
    build: ui
    ports:
      - "9000:9000"
    env_file:
      - secrets.env.example

volumes:
  api-data:
