services:
  refinance-api:
    build: .
    container_name: refinance-api
    ports:
      - "8000:8000"
    volumes:
      - refinance-api-data:/opt/data
    env_file:
      - secrets.env

volumes:
  refinance-api-data:
