services:
  api:
    build:
      context: .
      dockerfile: api/Dockerfile
    env_file:
      - secrets.env.example

  ui:
    build: 
      context: .
      dockerfile: ui/Dockerfile
    env_file:
      - secrets.env.example

  ui-new:
    build:
      context: ./ui-new
      dockerfile: Dockerfile
      target: prod
    depends_on:
      - api
  
  db:
    image: postgres:17
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: refinance
