name: Pytest

on:
  push:
  pull_request:

jobs:
  compose-up-and-pytest:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and Run Docker Compose
        run: |
          docker compose -f docker-compose.yml -f docker-compose.ci.yml up --build -d
      - name: Run pytest
        run: |
          docker compose -f docker-compose.yml -f docker-compose.ci.yml exec api pytest -v -s --log-level DEBUG
      - name: Stop and remove containers
        run: |
          docker compose down
